#!/usr/bin/env python3
"""SyllabAI Discord daily pulse.

Posts one embed per day to a Discord channel summarizing project state:
commits in the last 24h per repo, Drive-sync health verdict per repo,
and a link to the full Google Sheet dashboard.

Runs inside GitHub Actions (SyllabAI/syllabai). Stdlib only.

Env:
  GH_TOKEN   GitHub PAT (read across SyllabAI repos) - secret GH_DASHBOARD_TOKEN
  WEBHOOK    Discord webhook URL - secret DISCORD_WEBHOOK_URL
  SHEET_ID   dashboard spreadsheet id - variable GDRIVE_SHEET_ID (optional)
Gracefully skips when WEBHOOK is absent.
"""
import json
import os
import sys
import time
import urllib.parse
import urllib.request
from datetime import datetime, timedelta, timezone

GH_TOKEN = os.environ.get("GH_TOKEN", "")
WEBHOOK = os.environ.get("WEBHOOK", "")
SHEET_ID = os.environ.get("SHEET_ID", "")
FAILED = {"failure", "timed_out", "startup_failure", "action_required"}

GREEN, RED, AMBER = 0x2ECC71, 0xE74C3C, 0xF1C40F


def gh(path, params=None):
    url = f"https://api.github.com{path}"
    if params:
        url += "?" + urllib.parse.urlencode(params)
    req = urllib.request.Request(url, headers={
        "Authorization": f"token {GH_TOKEN}",
        "Accept": "application/vnd.github+json",
        "User-Agent": "syllabai-digest"})
    for attempt in range(3):
        try:
            with urllib.request.urlopen(req, timeout=30) as r:
                return json.loads(r.read().decode())
        except Exception as e:
            if attempt == 2:
                print(f"::warning::{path} failed: {e}")
                return None
            time.sleep(2 ** (attempt + 1))


def health(runs):
    if not runs:
        return "⚪"
    r0 = runs[0]
    if r0.get("status") in ("in_progress", "queued"):
        return "⏳"
    if (r0.get("conclusion") or "") in FAILED:
        return "🔴"
    ok = next((r for r in runs if r.get("conclusion") == "success"), None)
    if not ok:
        return "🔴"
    started = ok.get("run_started_at") or ok.get("created_at") or ""
    try:
        age = datetime.now(timezone.utc) - datetime.strptime(started, "%Y-%m-%dT%H:%M:%SZ")
    except Exception:
        return "🟡"
    h = age.total_seconds() / 3600
    return "🟢" if h <= 48 else ("🟡" if h <= 168 else "🔴")


def main():
    if not WEBHOOK:
        print("::notice::DISCORD_WEBHOOK_URL not set - daily pulse skipped")
        return
    if not GH_TOKEN:
        print("::error::GH_TOKEN missing")
        sys.exit(1)

    repos = gh("/user/repos", {"per_page": 100, "sort": "pushed",
                               "visibility": "all", "affiliation": "owner"}) or []
    since = (datetime.now(timezone.utc) - timedelta(hours=24)).strftime("%Y-%m-%dT%H:%M:%SZ")
    fields, any_red = [], False
    total_commits = 0
    for repo in sorted(repos, key=lambda r: r["name"]):
        full, name = repo["full_name"], repo["name"]
        commits = gh(f"/repos/{full}/commits", {"since": since, "per_page": 100}) or []
        n = len(commits) if isinstance(commits, list) else 0
        total_commits += n
        runs_data = gh(f"/repos/{full}/actions/runs", {"per_page": 15}) or {}
        runs = [r for r in runs_data.get("workflow_runs", [])
                if r.get("name") == "Google Drive Sync"]
        verdict = health(runs)
        any_red = any_red or verdict in ("🔴",)
        last = ""
        if n:
            msg = (commits[0].get("commit", {}).get("message") or "").splitlines()[0]
            last = f" · `{msg[:70]}`" if msg else ""
        fields.append({
            "name": f"{verdict} {name}",
            "value": f"**{n}** commit{'s' if n != 1 else ''} in 24h{last}",
            "inline": True,
        })

    desc = "Project state for the last 24 hours, straight from GitHub.\n"
    if SHEET_ID:
        desc += (f"\n📊 [Open the full dashboard]"
                 f"(https://docs.google.com/spreadsheets/d/{SHEET_ID}/edit)"
                 " — commits log, sync runs, Drive growth.\n")
    desc += f"\n**Total: {total_commits} commits today**"
    if any_red:
        desc += "\n\n⚠ At least one repo has a failing or stale Drive sync — check the dashboard."

    payload = {
        "username": "SyllabAI Pulse",
        "embeds": [{
            "title": "🌅 SyllabAI daily pulse",
            "description": desc,
            "color": RED if any_red else GREEN,
            "fields": fields,
            "footer": {"text": "Next pulse ~09:00 Dhaka · auto-generated by GitHub Actions"},
            "timestamp": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        }],
    }
    req = urllib.request.Request(WEBHOOK, data=json.dumps(payload).encode(),
                                 headers={"Content-Type": "application/json",
                                          "User-Agent": "SyllabAI-Notifier/1.0 (+https://github.com/SyllabAI)"})
    try:
        urllib.request.urlopen(req, timeout=20)
        print(f"[OK] pulse posted — {len(repos)} repos, {total_commits} commits in 24h")
    except Exception as e:
        print(f"::error::Discord webhook failed: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
